### ISSUE TITLE
logo contribution

### ISSUE THREAD

**Issue by reallinfo** [EclipseXuLu/DataHouse#1]
Hello @lucasxlu 

I guees this repository does not have a logo. Do you want me to design a logo? I will wait for feedback. Have a nice day!

**Comment by reallinfo** [comment]
I designed a logo inspired by the function and name of the software. What do you think? Please tell me if there is anything you want to change.

![dh](https://user-images.githubusercontent.com/36298335/47602050-c7567080-d9e1-11e8-9d0b-136cbf5416ba.jpg)

**Comment by reallinfo** [comment]
Sure, i sent a pr.

**Comment by reallinfo** [comment]
Hi again, @lucasxlu 

I forgot to make the final arrangements of the logo. So I sent a new pr. Now your logo is more clean! Please check it.

https://github.com/lucasxlu/DataHouse/pull/3

**Comment by lucasxlu** [comment]
Well, THX for your contribution! 😄
